
spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: http://gitlab.dafycredit.com/szqk-prod/prod-config-file.git
          force-pull: true
          username: 900002
          password: qq4920092
          search-paths: /*

eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://10.11.11.73:10010/eureka/,http://10.11.11.74:10010/eureka/



